<a href="https://colab.research.google.com/github/srujithach0-lang/Pandas_Analysis.ipynb/blob/main/customer_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
import numpy as np
# 1. Initialize the synthetic dataset
df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

# Task 1 — Clean the Data
Using the synthetic dataset below, write Python code to:

Impute missing values in age with the median and in city with the mode
Remove any duplicate rows

In [69]:
#Calculate the median of 'age'
median_age = df['age'].median()

#calculaing the mode of 'city'

mode_city = df['city'].mode()

#impute the missing values
#age with median
df['age'] = df['age'].fillna(median_age)
df['city'] = df['city'].fillna(mode_city)

print(median_age)
print(mode_city)

35.0
0     Delhi
1    Mumbai
Name: city, dtype: object

In [70]:
#Removing duplicate values
df_Cleaned = df.drop_duplicates()
df.drop_duplicates(inplace=True)

In [71]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0     NaN    Male          95000

In [72]:
# Check how many duplicate rows exist
print(df.duplicated().sum())

# View the duplicate rows
print(df[df.duplicated()])

# Remove duplicates, keep the first occurrence
df.drop_duplicates(inplace=True)

0
Empty DataFrame
Columns: [customer_id, age, city, gender, annual_income]
Index: []

# Task 2 — Encode Categorical Columns
After cleaning, encode the categorical columns:

Apply One-Hot Encoding to city
Apply Label Encoding to gender
Print the resulting dataframe.

In [73]:
df = pd.get_dummies(df, columns=["city"])

In [74]:
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000       False        False
3            4  35.0    Male         120000       False         True
5            5  40.0    Male          95000       False        False

In [75]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["gender_encoded"] = le.fit_transform(df["gender"])

In [76]:
df

,customer_id,age,gender,annual_income,city_Delhi,city_Mumbai,gender_encoded
0,1,25.0,Male,40000,False,True,1
1,2,35.0,Female,80000,True,False,0
2,3,35.0,Female,60000,False,False,0
3,4,35.0,Male,120000,False,True,1
5,5,40.0,Male,95000,False,False,1

# Task 3 — Scale Numerical Features
Scale age and annual_income using both methods below on the cleaned dataframe, and print the results of each:
Min-Max Scaling (using MinMaxScaler)
Standardisation (using StandardScaler)
In 2–3 sentences, explain when you would prefer one over the other.

In [77]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[["age", "annual_income"]] = scaler.fit_transform(df[["age", "annual_income"]])

In [78]:
df

,customer_id,age,gender,annual_income,city_Delhi,city_Mumbai,gender_encoded
0,1,0.000000,Male,0.0000,False,True,1
1,2,0.666667,Female,0.5000,True,False,0
2,3,0.666667,Female,0.2500,False,False,0
3,4,0.666667,Male,1.0000,False,True,1
5,5,1.000000,Male,0.6875,False,False,1

In [79]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[["age", "annual_income"]] = scaler.fit_transform(df[["age", "annual_income"]])

In [80]:
df

,customer_id,age,gender,annual_income,city_Delhi,city_Mumbai,gender_encoded
0,1,-1.837117,Male,-1.410970,False,True,1
1,2,0.204124,Female,0.036179,True,False,0
2,3,0.204124,Female,-0.687396,False,False,0
3,4,0.204124,Male,1.483328,False,True,1
5,5,1.224745,Male,0.578860,False,False,1

# Task 3 Explanation: MinMaxScaler vs. StandardScaler
➡️Prefer MinMaxScaler when your data does not follow a normal distribution, you have strictly bounded limits, or your algorithm specifically requires features to be on an exact scale between 0 and 1 (like neural networks or distance-based algorithms like KNN).

➡️Prefer StandardScaler when your data follows a normal (Gaussian) distribution or contains extreme outliers, because standardisation does not compress outliers into a tiny, squished range like Min-Max scaling does. Many machine learning estimators (like linear regression, logistic regression, and SVMs) assume that all features are centered around zero with a variance of one.