<a href="https://colab.research.google.com/github/srujithach0-lang/Pandas_Analysis.ipynb/blob/main/used_car_price_baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1 — Explore and Identify Issues Load the dataset and use df.info(), df.describe(), and df.shape to report at least three data quality problems you observe (e.g., wrong dtypes, nulls, impossible values).

In [34]:
import pandas as pd

df = pd.read_csv("/content/used_cars_messy.csv")
df.shape
df.head()
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [35]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

Task 2 — Clean the Data Fix the issues identified: drop null target rows, impute missing input features, strip and lowercase the brand column, extract numeric values from the mileage column, and remove duplicates

In [39]:
import numpy as np  # <--- Add this line here to fix the NameError

# 1. Drop rows where the target variable (selling_price) is missing
df = df.dropna(subset=['selling_price'])

# 2. Strip whitespaces and lowercase the 'brand' column
df['brand'] = df['brand'].astype(str).str.strip().str.lower()

# 3. Extract numeric values from the 'mileage' column
df['mileage'] = df['mileage'].astype(str).str.extract(r'([\d\.]+)').astype(float)

# 4. Impute missing input features
num_cols = df.select_dtypes(include=[np.number]).columns
for col in num_cols:
    if col != 'selling_price':
        df[col] = df[col].fillna(df[col].median())

cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# 5. Remove duplicate rows
df = df.drop_duplicates()

print(f"Cleaned dataset shape: {df.shape}")

Cleaned dataset shape: (15324, 14)

In [37]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,honda,City,3,48959,Dealer,Petrol,Manual,19.67,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.40,2179.0,88.50,8.0,925000.0
4,14160,Mahindra XUV500,mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,1248.0,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,hyundai,i20,2,15000,Dealer,Petrol,Manual,18.60,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

Task 3 — Compute Baseline MAE Build a baseline model that predicts the mean selling_price for every record. Calculate and print the MAE of this baseline on the full cleaned dataset.

We will predict the mean of the selling_price for every single car and calculate the Mean Absolute Error ($MAE$).$$MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}|$$

In [38]:
from sklearn.metrics import mean_absolute_error

# 1. Define actual values
y_true = df['selling_price']

# 2. Create baseline predictions (the mean of selling_price for every row)
mean_price = y_true.mean()
y_pred_baseline = [mean_price] * len(df)

# 3. Calculate Mean Absolute Error
baseline_mae = mean_absolute_error(y_true, y_pred_baseline)

print(f"Baseline Mean Price: {mean_price:.2f}")
print(f"Baseline Mean Absolute Error (MAE): {baseline_mae:.2f}")

Baseline Mean Price: 1036605.06
Baseline Mean Absolute Error (MAE): 867382.29